name: Second Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: run multiple commands
        run: |
          echo "running multiple cmds"
          date1235

      - name: complete
        run: echo "done!"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: date

      - name: list content
        run: cat /etc/os-release
        
